"""empty message

Revision ID: 0a95ba66ac2c
Revises: 
Create Date: 2021-10-01 02:07:44.604951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a95ba66ac2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Дата', sa.DateTime(), nullable=True),
    sa.Column('Название', sa.String(length=50), nullable=False),
    sa.Column('Количество', sa.Integer(), nullable=False),
    sa.Column('Рссстояние', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects')
    # ### end Alembic commands ###
